version: '3.8'
services:
  php:
    image: public.ecr.aws/e4f9i3i0/html:php
    ports:
      - "8082:80"
    env_file:
     - ./php.env    
    environment:
        - SERVERNAME=${SERVERNAME}
        - DBNAME= ${DBNAME}
        - USER_NAME= ${USERNAME}
        - PASSWORD= ${PASSWORD}  
    networks:
      - network-backend
  db:
    image: public.ecr.aws/e4f9i3i0/html:db
    ports:
      - "3306:3306"
    networks:
      - network-backend
    volumes:  
      - sql_data:/var/lib/mysql/  


networks:
  network-backend:        

volumes:
  sql_data:
