apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-deployment
  namespace: se-ns
  labels:
    app: php    
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php             # Selector matches Pods with label 'app: db'
  template:
    metadata:
      labels:
        app: php            # Label assigned to Pods created by this Deployment
    spec:
      containers:
      - name: php
        image: public.ecr.aws/e4f9i3i0/html:v
        ports:
        - containerPort: 80

        env:    
        - name: SERVERNAME                         
          valueFrom:
            configMapKeyRef:
              name: game-demo           
              key: servername  

        - name: DB_NAME                           
          valueFrom:
            configMapKeyRef:
              name: game-demo           
              key: dbname

        - name: USERNAME                         
          valueFrom:
            configMapKeyRef:
              name: game-demo           
              key: username_db        

        - name: PASSDB
          valueFrom: 
            secretKeyRef: 
              name: secret-sa-sample
              key: pass     
           

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: se-ns
spec:
  type: LoadBalancer
  selector:
    app: php
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 80
    targetPort: 80
    

---



