apiVersion: v1
kind: PersistentVolume
metadata:
  name: webpv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ebs-claims
  claimRef:
    name: webpvc
    namespace: serv-ns
  awsElasticBlockStore:
    volumeID: vol-02db2275c951184c8

    