apiVersion: v1
kind: PersistentVolume
metadata:
  name: newpv 
  # labels:
  #   type: local 
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce 
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ebs-claims 
  claimRef:
    name: newpvc
    namespace: se-ns
  hostPath:
    path: /var/lib/mysql/
