apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: newpvc
  namespace: se-ns
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  
  storageClassName: ebs-claims
  

