apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webpvc
  namespace: serv-ns
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  
  storageClassName: ebs-claims

  