# eksctl create iamserviceaccount \
#     --name ebs-csi-controller-sa \
#     --namespace serv-ns \
#     --cluster my-cluster \
#     --attach-policy-arn arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy \
#     --override-existing-serviceaccounts \
#     --approve \
#     --role-only \
#     --role-name AmazonEKS_EBS_CSI_DriverRole   

# export SERVICE_ACCOUNT_ROLE_ARN=$(aws iam get-role --role-name AmazonEKS_EBS_CSI_DriverRole | jq -r '.Role.Arn') 


apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-claims
  namespace: serv-ns
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer


